### ISSUE TITLE
Left Join

### ISSUE THREAD

**Issue by martinnedopil** [bingzer/DbQuery#30]
there is no implementation for left join. I added this implementation into your file, but I`m using Eclipse so there is no way to do changes and push to server.

**Comment by patrykmat** [comment]
Hi,
I am interesting in using this library, but I cannot find LEFT JOINs in Master branch - is the code from the development branch production ready?

**Comment by martinnedopil** [comment]
Hi Patryk,

I do not know. I didnt post my code to dev branch I just sent it via e/mail
to bingzer and I do not know
if he added this to master branch.

Martin



pá 3. 6. 2016 v 10:21 odesílatel Patryk Matuszewski <
notifications@github.com> napsal:

**Comment by bingzer** [comment]
Hi All, Sorry for the lack of activities. v 2.2 is in Dev branch it has martin's changes (left join, outer join) and there are also some refactoring changes. I haven't put any tests for left/outer joins just yet.

What happened was the Travis CI Build changes and I couldn't figure it out how to make it work then I gave up before merging these changes to master. I'm away from Android development nowadays - Feel free to PR

**Comment by bingzer** [comment]
The v2.2 should be up in maven central

```
repositories {
    mavenCentral()
}

dependencies {
    compile (group:'com.bingzer.android.dbv', name: 'dbquery', version:'2.2.0')
}
```
